services:
  db:
    image: postgis/postgis:18-3.6
    container_name: sim_postgres_db
    platform: linux/amd64
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - sim_db:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sim_postgres_admin
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8082:80"  # Host port 8082 -> container port 80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    depends_on:
      - db
    volumes:
      - sim_db:/var/lib/pgadmin

volumes:
  sim_db: